server:
  port: 8083
  servlet:
    context-path: /pay-service

# spring-boot dubbo config
dubbo:
  application:
    name: springboot-pay-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881